# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:11.12.0-stretch
      environment:
        NODE_ENV: test
  working_directory: ~/iam-gateway

install_npm_packages: &install_npm_packages
  run:
    name: Install Npm Dependencies
    command: yarn install

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/iam-gateway

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths: .

filters: &filters
  filters:
    branches:
      only:
        - develop
        - master

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - *install_npm_packages

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - *persist_to_workspace

  lint_code:
    <<: *defaults
    steps:
      - *attach_workspace
      - *install_npm_packages
      - run:
          name: Run iam-gateway lint test
          command: yarn lint
      - *persist_to_workspace

  build_docker:
    <<: *defaults
    steps:
      - *attach_workspace
      - *install_npm_packages
      - run:
          name: Compile ES6 to ES5 in dist
          command: yarn build
      - setup_remote_docker
      - run:
          name: Build the staging docker image
          command: docker build -f docker/release/Dockerfile -t iam-gateway:0.0.1 .
      - run:
          name: Tag the staging docker image
          command: docker tag iam-gateway:0.0.1 shopinc/iam-gateway:0.0.1
      - run:
          name: Log in to hub.docker.com
          command: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
      - run:
          name: Push the updated docker image to docker hub
          command: docker push shopinc/iam-gateway:0.0.1
      - run:
          name: Logout of docker hub
          command: docker logout $DOCKER_REGISTRY 
      - *persist_to_workspace

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_code
      - lint_code:
          requires:
            - checkout_code
      - build_docker:
          requires:
            - checkout_code
            - lint_code
          <<: *filters
