// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity.proto

package protobuf

import (
	"context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoogleIdToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoogleIdToken) Reset()         { *m = GoogleIdToken{} }
func (m *GoogleIdToken) String() string { return proto.CompactTextString(m) }
func (*GoogleIdToken) ProtoMessage()    {}
func (*GoogleIdToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{0}
}

func (m *GoogleIdToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoogleIdToken.Unmarshal(m, b)
}
func (m *GoogleIdToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoogleIdToken.Marshal(b, m, deterministic)
}
func (m *GoogleIdToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoogleIdToken.Merge(m, src)
}
func (m *GoogleIdToken) XXX_Size() int {
	return xxx_messageInfo_GoogleIdToken.Size(m)
}
func (m *GoogleIdToken) XXX_DiscardUnknown() {
	xxx_messageInfo_GoogleIdToken.DiscardUnknown(m)
}

var xxx_messageInfo_GoogleIdToken proto.InternalMessageInfo

func (m *GoogleIdToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string            `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Profile              *UserInfo_Profile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	Token                string            `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetProfile() *UserInfo_Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *UserInfo) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserInfo_Profile struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	LastUpdated          string   `protobuf:"bytes,2,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo_Profile) Reset()         { *m = UserInfo_Profile{} }
func (m *UserInfo_Profile) String() string { return proto.CompactTextString(m) }
func (*UserInfo_Profile) ProtoMessage()    {}
func (*UserInfo_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_61c7956abb761639, []int{1, 0}
}

func (m *UserInfo_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo_Profile.Unmarshal(m, b)
}
func (m *UserInfo_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo_Profile.Marshal(b, m, deterministic)
}
func (m *UserInfo_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo_Profile.Merge(m, src)
}
func (m *UserInfo_Profile) XXX_Size() int {
	return xxx_messageInfo_UserInfo_Profile.Size(m)
}
func (m *UserInfo_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo_Profile proto.InternalMessageInfo

func (m *UserInfo_Profile) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *UserInfo_Profile) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func init() {
	proto.RegisterType((*GoogleIdToken)(nil), "protobuf.GoogleIdToken")
	proto.RegisterType((*UserInfo)(nil), "protobuf.UserInfo")
	proto.RegisterType((*UserInfo_Profile)(nil), "protobuf.UserInfo.Profile")
}

func init() { proto.RegisterFile("identity.proto", fileDescriptor_61c7956abb761639) }

var fileDescriptor_61c7956abb761639 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0xae, 0x6e, 0x9d, 0x45, 0x85, 0x41, 0xb0, 0xe4, 0x54, 0x0a, 0xc2, 0x9e, 0x72,
	0x58, 0xbd, 0x79, 0xf4, 0xb0, 0xf4, 0x22, 0xb2, 0xda, 0x07, 0xc8, 0x9a, 0xe9, 0x12, 0x4c, 0x93,
	0x92, 0x8d, 0x82, 0x8f, 0xe8, 0x5b, 0x49, 0xd3, 0xd4, 0xad, 0x78, 0xca, 0xfc, 0xc3, 0x37, 0x99,
	0x8f, 0x81, 0x4b, 0xad, 0xc8, 0x06, 0x1d, 0xbe, 0x44, 0xe7, 0x5d, 0x70, 0x98, 0xc5, 0x67, 0xfb,
	0xd1, 0x94, 0xb7, 0x70, 0xb1, 0x76, 0x6e, 0x67, 0xa8, 0x52, 0xaf, 0xee, 0x9d, 0x2c, 0x5e, 0xc3,
	0x69, 0xe8, 0x8b, 0x9c, 0x15, 0x6c, 0x79, 0xbe, 0x19, 0x42, 0xf9, 0xcd, 0x20, 0xab, 0xf7, 0xe4,
	0x2b, 0xdb, 0x38, 0x44, 0x98, 0x59, 0xd9, 0x52, 0x22, 0x62, 0xdd, 0x8f, 0x51, 0x2b, 0xb5, 0xc9,
	0x8f, 0x87, 0xb1, 0x18, 0xf0, 0x1e, 0xe6, 0x9d, 0x77, 0x8d, 0x36, 0x94, 0x9f, 0x14, 0x6c, 0xb9,
	0x58, 0x71, 0x31, 0x6e, 0x16, 0xe3, 0x77, 0xe2, 0x79, 0x20, 0x36, 0x23, 0x7a, 0x50, 0x98, 0x4d,
	0x14, 0xf8, 0x1a, 0xe6, 0x89, 0x44, 0x0e, 0x99, 0x6e, 0xe5, 0x8e, 0x6a, 0x6f, 0x92, 0xc4, 0x6f,
	0xc6, 0x02, 0x16, 0x46, 0xee, 0x43, 0xdd, 0x29, 0x19, 0x48, 0x25, 0x9d, 0x69, 0x6b, 0xf5, 0x04,
	0x57, 0x55, 0x3a, 0xc7, 0x0b, 0xf9, 0x4f, 0xfd, 0x46, 0xf8, 0x00, 0xf0, 0xe8, 0x49, 0x06, 0xea,
	0xa5, 0xf0, 0xe6, 0x20, 0xf9, 0xe7, 0x36, 0x1c, 0xff, 0xdb, 0x97, 0x47, 0xdb, 0xb3, 0xd8, 0xbc,
	0xfb, 0x09, 0x00, 0x00, 0xff, 0xff, 0x14, 0xea, 0xce, 0x36, 0x65, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Let's create the identity management client interface
// These represent the gRPC procedures that we had in the sever.

type IdentityServiceClient interface {
	CreateUser(ctx context.Context, in *GoogleIdToken, opts ...grpc.CallOption) (error, *UserInfo)
}

type simpleServerClient struct {
	connection *grpc.ClientConn
}

func NewSimpleServerClient(connection *grpc.ClientConn) IdentityServiceClient {
	return &simpleServerClient{connection}
}

func (simpleClient *simpleServerClient) CreateUser(ctx context.Context, in *GoogleIdToken, opts ...grpc.CallOption) (error, *UserInfo) {
	out := new(UserInfo)
	err := simpleClient.connection.Invoke(ctx, "/protobuf.IdentityService/CreateUser", in, out, opts...)

	if err != nil {
		return err, nil
	}

	return nil, out
}
